export const ZONES_OPTIONS = [
  { id: 'casco_antiguo', label: 'Casco Antiguo' },
  { id: 'triana', label: 'Triana' },
  { id: 'los_remedios', label: 'Los Remedios' },
  { id: 'nervion', label: 'Nervion' },
  { id: 'san_pablo', label: 'San Pablo - Santa Justa' },
  { id: 'este_alcosa', label: 'Este - Alcosa - Torreblanca' },
  { id: 'cerro_amate', label: 'Cerro - Amate' },
  { id: 'sur', label: 'Sur' },
  { id: 'bellavista', label: 'Bellavista - La Palmera' },
  { id: 'macarena', label: 'Macarena' },
  { id: 'norte', label: 'Norte' },
  { id: 'viapol', label: 'Viapol' },
  { id: 'plantinar', label: 'El Plantinar' },
  { id: 'juncal', label: 'El Juncal' },
  { id: 'gran_plaza', label: 'Gran Plaza' },
  { id: 'otros', label: 'Otro/Alrededores' },
];
