import { StyleSheet } from 'react-native';
import {
  borderRadius,
  colors,
  semanticRadii,
  semanticSizes,
  sizes,
  spacing,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surfaceMutedAlt,
  },
  flexFill: {
    flex: 1,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s10,
    minHeight: sizes.s56,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    overflow: 'hidden',
  },
  headerFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  headerProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
    flex: 1,
  },
  headerAvatar: {
    width: semanticSizes.avatarXs,
    height: semanticSizes.avatarXs,
    borderRadius: borderRadius.s18,
  },
  headerName: {
    fontSize: 16,
    fontWeight: '600',
  },
  headerMenuButton: {
    width: sizes.s30,
    height: sizes.s30,
    borderRadius: borderRadius.s14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSpacer: {
    width: sizes.s22,
  },
  matchMenu: {
    alignSelf: 'flex-end',
    marginRight: spacing.md,
    marginTop: spacing.xs,
    borderRadius: semanticRadii.soft,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
    overflow: 'hidden',
  },
  matchMenuItem: {
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.s10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s8,
  },
  matchMenuText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.errorDark,
  },
  typingRow: {
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  typingText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  typingFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  assignmentPanel: {
    marginHorizontal: spacing.md,
    marginTop: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s14,
    gap: spacing.s10,
  },
  assignmentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  assignmentHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s8,
  },
  assignmentTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  assignmentSubtitle: {
    marginTop: spacing.xs,
    fontSize: 12,
    color: colors.textSecondary,
  },
  assignmentStatusPill: {
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.surfaceLight,
  },
  assignmentStatusText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
  },
  assignActions: {
    flexDirection: 'row',
    gap: spacing.s10,
    flexWrap: 'wrap',
    marginTop: spacing.s6,
  },
  assignmentNote: {
    width: '100%',
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
  },
  assignButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.s10,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.text,
  },
  assignButtonDisabled: {
    backgroundColor: colors.textMuted,
  },
  assignButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  assignButtonTextDisabled: {
    color: colors.surfaceLight,
  },
  offerCard: {
    borderRadius: semanticRadii.soft,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    padding: spacing.s12,
    backgroundColor: colors.glassUltraLightAlt,
  },
  offerTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  offerSubtitle: {
    marginTop: spacing.s6,
    fontSize: 12,
    color: colors.textSecondary,
  },
  offerActions: {
    marginTop: spacing.s10,
    flexDirection: 'row',
    gap: spacing.s10,
  },
  offerButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
  },
  offerAccept: {
    backgroundColor: colors.text,
  },
  offerReject: {
    backgroundColor: colors.errorSoft,
  },
  offerButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  offerRejectText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.errorDark,
  },
  roommatesPanel: {
    marginHorizontal: spacing.md,
    marginTop: spacing.s12,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s14,
  },
  glassCard: {
    borderRadius: semanticRadii.card,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    shadowColor: colors.shadowDark,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  glassFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  roommatesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  roommatesHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s8,
  },
  roommatesTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
  },
  roommatesBadge: {
    minWidth: semanticSizes.badge,
    height: semanticSizes.badge,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.primarySoftAlt,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.s6,
  },
  roommatesBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  roommatesToggle: {
    width: sizes.s28,
    height: sizes.s28,
    borderRadius: borderRadius.s14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  roommatesEmpty: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.textSecondary,
  },
  roommatesList: {
    marginTop: spacing.s10,
    gap: spacing.s6,
  },
  roommateRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  roommateName: {
    fontSize: 12,
    color: colors.text,
    fontWeight: '600',
  },
  roommateRoom: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  messagesList: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s20,
    gap: spacing.s12,
  },
  messagesFooter: {
    height: sizes.s140,
  },
  messageRow: {
    flexDirection: 'row',
  },
  messageRowMine: {
    justifyContent: 'flex-end',
  },
  messageRowOther: {
    justifyContent: 'flex-start',
  },
  bubble: {
    maxWidth: '74%',
    paddingHorizontal: spacing.s18,
    paddingTop: spacing.s8,
    paddingBottom: spacing.s10,
    borderRadius: 24,
    overflow: 'hidden',
  },
  bubbleMine: {
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    shadowColor: colors.shadowDark,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  bubbleOther: {
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    shadowColor: colors.shadowDark,
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 10,
    elevation: 1,
  },
  bubbleGlassFill: {
    ...StyleSheet.absoluteFillObject,
  },
  bubbleGlassFillMine: {
    backgroundColor: colors.primarySoftAlt,
  },
  bubbleGlassFillOther: {
    backgroundColor: colors.glassUltraLightAlt,
  },
  bubbleText: {
    fontSize: 14,
    lineHeight: 21,
    letterSpacing: 0.1,
  },
  bubbleTextMine: {
    color: colors.text,
  },
  bubbleTextOther: {
    color: colors.text,
  },
  bubbleMeta: {
    marginTop: spacing.s6,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  bubbleMetaOther: {
    justifyContent: 'flex-start',
  },
  bubbleTime: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  bubbleStatus: {
    fontSize: 10,
    color: colors.primary,
    fontWeight: '600',
  },
  scrollToEndButton: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.xs,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s8,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    flexDirection: 'row',
    gap: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: colors.shadowDark,
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 2,
  },
  scrollToEndFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
    borderRadius: semanticRadii.pill,
  },
  scrollToEndText: {
    fontSize: 11,
    color: colors.text,
    fontWeight: '600',
  },
  inputContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: spacing.s40,
    paddingBottom: spacing.s10,
  },
  inputFooter: {
    paddingTop: spacing.sm,
  },
  inputGlass: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.s12,
    borderRadius: borderRadius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.lavenderBorder,
  },
  unmatchedNotice: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.s12,
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.s12,
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  unmatchedNoticeText: {
    fontSize: 12,
    color: colors.textSecondary,
    fontWeight: '600',
    textAlign: 'center',
  },
  inputGlassFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassMid,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s10,
    gap: spacing.s10,
  },
  input: {
    flex: 1,
    paddingVertical: spacing.s10,
    paddingHorizontal: spacing.s14,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.glassUltraLightAlt,
    fontSize: 14,
    color: colors.text,
  },
  sendButton: {
    width: spacing.s40,
    height: spacing.s40,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlayLight,
  },
  modalContent: {
    backgroundColor: colors.background,
    borderTopLeftRadius: semanticRadii.sheet,
    borderTopRightRadius: semanticRadii.sheet,
    padding: spacing.s20,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  modalSubtitle: {
    marginTop: spacing.s6,
    fontSize: 12,
    color: colors.textSecondary,
  },
  modalList: {
    marginTop: spacing.s12,
  },
  modalRoomItem: {
    paddingVertical: spacing.s10,
    paddingHorizontal: spacing.s12,
    borderRadius: semanticRadii.soft,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.s10,
  },
  modalRoomItemActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  modalRoomTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  modalRoomTitleActive: {
    color: colors.primary,
  },
  modalRoomMeta: {
    marginTop: spacing.xs,
    fontSize: 12,
    color: colors.textSecondary,
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.s10,
    marginTop: spacing.s12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: spacing.s10,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
  },
  modalCancel: {
    backgroundColor: colors.surfaceLight,
  },
  modalCancelText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  modalConfirmText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  modalConfirm: {
    backgroundColor: colors.primary,
  },
  modalButtonDisabled: {
    backgroundColor: colors.primaryMuted,
  },
});
