import { StyleSheet } from 'react-native';
import {
  borderRadius,
  colors,
  semanticRadii,
  semanticSizes,
  sizes,
  spacing,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surfaceMutedAlt,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  headerFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  headerIconButton: {
    width: semanticSizes.control,
    height: semanticSizes.control,
    borderRadius: borderRadius.s18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  content: {
    flex: 1,
    padding: spacing.s20,
  },
  sectionBlock: {
    marginBottom: spacing.s18,
  },
  sectionTitleMuted: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: spacing.s10,
  },
  sectionCard: {
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
    padding: spacing.md,
    gap: spacing.s12,
    shadowOpacity: 0,
    elevation: 0,
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.s10,
  },
  photoTile: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: borderRadius.md,
    overflow: 'hidden',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  photoPressArea: {
    width: '100%',
    height: '100%',
  },
  deleteButton: {
    position: 'absolute',
    top: spacing.s6,
    right: spacing.s6,
    width: semanticSizes.iconLg,
    height: semanticSizes.iconLg,
    borderRadius: borderRadius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.dangerOverlay,
  },
  deleteButtonText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.background,
  },
  primaryBadge: {
    position: 'absolute',
    bottom: spacing.s6,
    left: spacing.s6,
    right: spacing.s6,
    paddingVertical: spacing.xs,
    backgroundColor: colors.textOverlayStrong,
    borderRadius: borderRadius.sm,
  },
  primaryBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.background,
    textAlign: 'center',
  },
  photoHint: {
    marginTop: spacing.s10,
    fontSize: 12,
    color: colors.textSecondary,
  },
  photoUploadingText: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.text,
    fontWeight: '600',
  },
  profileHeader: {
    alignItems: 'center',
    marginBottom: spacing.s20,
  },
  avatarShell: {
    width: semanticSizes.avatarLg,
    height: semanticSizes.avatarLg,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: {
    width: sizes.s86,
    height: sizes.s86,
    borderRadius: semanticRadii.pill,
  },
  avatarPlaceholder: {
    width: sizes.s86,
    height: sizes.s86,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarEdit: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: sizes.s28,
    height: sizes.s28,
    borderRadius: borderRadius.s14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 2,
  },
  profileHint: {
    marginTop: spacing.s12,
    fontSize: 12,
    color: colors.textSecondary,
  },
  editPhotosButton: {
    marginTop: spacing.s12,
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.s12,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  editPhotosText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  switchLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.s10,
  },
  inlineLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: spacing.s10,
  },
  checkGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.s10,
    marginBottom: spacing.md,
  },
  checkItem: {
    width: '48%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
    paddingVertical: spacing.s12,
    paddingHorizontal: spacing.s12,
    borderRadius: borderRadius.s14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  checkItemActive: {
    borderColor: colors.text,
  },
  checkBox: {
    width: semanticSizes.iconSm,
    height: semanticSizes.iconSm,
    borderRadius: borderRadius.s6,
    borderWidth: 1,
    borderColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  checkBoxActive: {
    backgroundColor: colors.text,
  },
  checkLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  checkLabelActive: {
    color: colors.text,
  },
  switchRow: {
    flexDirection: 'row',
    gap: spacing.s10,
    marginBottom: spacing.md,
  },
  switchButton: {
    flex: 1,
    paddingVertical: spacing.s10,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
  },
  switchButtonActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  switchButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  switchButtonTextActive: {
    color: colors.background,
  },
  budgetContainer: {
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  budgetValues: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  budgetValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  situacionContainer: {
    marginBottom: spacing.md,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.sm,
    color: colors.textDark,
  },
  situacionButtons: {
    flexDirection: 'row',
    gap: spacing.s12,
  },
  situacionButton: {
    flex: 1,
    padding: spacing.s12,
    borderRadius: borderRadius.s10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  situacionButtonActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  situacionButtonText: {
    textAlign: 'center',
    fontSize: 14,
    color: colors.textSecondary,
  },
  situacionButtonTextActive: {
    color: colors.background,
    fontWeight: '600',
  },
  sliderTrack: {
    height: spacing.s6,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.border,
  },
  sliderTrackActive: {
    position: 'absolute',
    height: spacing.s6,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.text,
  },
  sliderThumb: {
    position: 'absolute',
    width: semanticSizes.thumb,
    height: semanticSizes.thumb,
    borderRadius: borderRadius.s10,
    backgroundColor: colors.text,
    borderWidth: 2,
    borderColor: colors.background,
    top: -7,
  },
  sliderTicks: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  sliderTick: {
    width: spacing.xxs,
    height: spacing.s6,
    backgroundColor: colors.disabled,
  },
  sliderLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.s6,
  },
  sliderLabel: {
    fontSize: 11,
    color: colors.textSecondary,
  },
});
