import { StyleSheet } from 'react-native';
import {
  borderRadius,
  colors,
  semanticRadii,
  semanticSizes,
  shadows,
  sizes,
  spacing,
} from '../../theme';
import { commonStyles } from '../common';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surfaceMutedAlt,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.s12,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  headerFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  headerTitleWrap: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  headerSubtitle: {
    marginTop: spacing.xs,
    fontSize: 12,
    color: colors.textSecondary,
  },
  headerAction: {
    width: semanticSizes.headerAction,
    height: semanticSizes.headerAction,
    borderRadius: borderRadius.s18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 4,
  },
  headerActionDisabled: {
    opacity: 0.5,
  },
  content: {
    padding: spacing.s20,
    gap: spacing.md,
  },
  sectionCard: {
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
    paddingHorizontal: spacing.s18,
    paddingVertical: spacing.s18,
    minHeight: sizes.s72,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: spacing.s10,
  },
  loadingState: {
    alignItems: 'center',
    paddingVertical: spacing.lg,
    gap: spacing.sm,
  },
  loadingText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xl,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  emptyStateInline: {
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.s20,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  emptyTitle: {
    marginTop: spacing.s12,
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
  },
  emptySubtitle: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  addButton: {
    marginTop: spacing.s12,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.primary,
  },
  addButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  flatSelectorLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  flatChips: {
    flexDirection: 'row',
    gap: spacing.s10,
    paddingBottom: spacing.s6,
  },
  flatChip: {
    ...commonStyles.chip,
  },
  flatChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primarySoft,
  },
  flatChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  flatChipTextActive: {
    color: colors.primary,
  },
  monthRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: spacing.s6,
  },
  monthButton: {
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s8,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  monthLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  summaryCard: {
    padding: spacing.md,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
    alignItems: 'center',
    gap: spacing.s6,
  },
  summaryTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  summarySubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  summaryAmount: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
  },
  settlementButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.s10,
    borderRadius: borderRadius.s14,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  settlementButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textStrong,
  },
  expenseList: {
    gap: spacing.s12,
  },
  expenseCard: {
    padding: spacing.s14,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  expenseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.s12,
  },
  expenseTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  expenseAside: {
    alignItems: 'flex-end',
    gap: spacing.s6,
  },
  amountBadge: {
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primarySoft,
  },
  amountBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.primary,
  },
  avatarStack: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarCircle: {
    width: sizes.s26,
    height: sizes.s26,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    borderRadius: semanticRadii.pill,
    resizeMode: 'cover',
  },
  avatarText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textMuted,
  },
  avatarOverflow: {
    backgroundColor: colors.surfaceLight,
  },
  avatarOverflowText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  expenseMeta: {
    marginTop: spacing.s6,
    fontSize: 12,
    color: colors.textSecondary,
  },
  expenseNote: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.textMuted,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlayLight,
  },
  modalContent: {
    backgroundColor: colors.glassUltraLightAlt,
    borderTopLeftRadius: semanticRadii.sheet,
    borderTopRightRadius: semanticRadii.sheet,
    padding: spacing.s20,
    maxHeight: '80%',
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    overflow: 'hidden',
  },
  modalGlassFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassSurface,
  },
  modalScroll: {
    paddingBottom: spacing.s12,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.text,
  },
  modalSubtitle: {
    marginTop: spacing.s6,
    fontSize: 12,
    color: colors.textSecondary,
  },
  modalHeaderDivider: {
    marginTop: spacing.s12,
    height: 1,
    backgroundColor: colors.glassBorderSoft,
  },
  modalField: {
    marginTop: spacing.s12,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  scopeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  scopeChip: {
    ...commonStyles.chip,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  scopeChipActive: {
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  scopeText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  scopeTextActive: {
    color: colors.primary,
  },
  participantsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.s10,
  },
  participantChip: {
    ...commonStyles.chip,
    borderColor: colors.glassBorder,
    backgroundColor: colors.glassUltraLightAlt,
  },
  participantChipActive: {
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  participantText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  participantTextActive: {
    color: colors.primary,
  },
  participantsEmpty: {
    marginTop: spacing.sm,
    fontSize: 12,
    color: colors.textSecondary,
  },
  participantsHint: {
    marginTop: spacing.sm,
    fontSize: 11,
    color: colors.textTertiary,
  },
  categoryChip: {
    ...commonStyles.chip,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  categoryChipActive: {
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  categoryTextActive: {
    color: colors.primary,
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: spacing.s6,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    borderRadius: borderRadius.md,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.s12,
    fontSize: 13,
    color: colors.text,
    backgroundColor: colors.glassSurface,
  },
  modalTextArea: {
    minHeight: sizes.s72,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.s10,
    marginTop: spacing.md,
  },
  modalButton: {
    flex: 1,
    height: sizes.s44,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancel: {
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  modalCancelText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textStrong,
  },
  modalConfirm: {
    backgroundColor: colors.primary,
  },
  modalConfirmText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  modalButtonDisabled: {
    backgroundColor: colors.primaryMuted,
  },
});
