import { StyleSheet } from 'react-native';
import {
  borderRadius,
  colors,
  semanticRadii,
  semanticSizes,
  sizes,
  spacing,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surfaceMutedAlt,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  headerFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  headerSpacer: {
    width: sizes.s48,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    flex: 1,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.s12,
  },
  headerIconButton: {
    width: semanticSizes.control,
    height: semanticSizes.control,
    borderRadius: borderRadius.s18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerIconButtonDisabled: {
    opacity: 0.6,
  },
  headerIconDanger: {
    backgroundColor: colors.errorSoft,
    borderColor: colors.errorBorder,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.s20,
    paddingTop: spacing.s20,
  },
  tabsContainer: {
    flexDirection: 'row',
    gap: spacing.s12,
    marginBottom: spacing.s20,
  },
  tabButton: {
    flex: 1,
    paddingVertical: spacing.s10,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    alignItems: 'center',
    backgroundColor: colors.glassUltraLightAlt,
  },
  tabButtonActive: {
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: colors.primary,
  },
  identityCard: {
    alignItems: 'center',
    marginBottom: 28,
    paddingVertical: spacing.s18,
    paddingHorizontal: spacing.s18,
    borderRadius: semanticRadii.sheet,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
    shadowOpacity: 0,
    elevation: 0,
  },
  avatarWrap: {
    width: semanticSizes.avatarLg,
    height: semanticSizes.avatarLg,
    borderRadius: semanticRadii.pill,
    overflow: 'hidden',
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.s12,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  avatarPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  identityName: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.text,
  },
  identityBadges: {
    marginTop: spacing.s10,
    alignItems: 'center',
    gap: spacing.sm,
  },
  identityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  identityBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  identityBadgeLight: {
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  identityBadgeLightText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  identityBadgeMini: {
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.s6,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  identityBadgeMiniText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.primary,
  },
  profileStatusRow: {
    alignItems: 'center',
    marginTop: spacing.s14,
    paddingVertical: spacing.s10,
    paddingHorizontal: spacing.s14,
  },
  profileStatusTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: spacing.sm,
  },
  profileStatusText: {
    fontSize: 14,
    fontWeight: '600',
  },
  profileStatusSubtext: {
    fontSize: 11,
    fontWeight: '500',
  },
  photoScroller: {
    gap: spacing.s12,
    paddingRight: spacing.sm,
  },
  photoTileWide: {
    width: sizes.s140,
    height: sizes.s180,
    borderRadius: semanticRadii.card,
    overflow: 'hidden',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photoTileImage: {
    width: '100%',
    height: '100%',
  },
  section: {
    marginBottom: 28,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  sectionMutedTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textSecondary,
    marginBottom: spacing.s12,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
    marginBottom: spacing.s12,
  },
  flatPager: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
    gap: spacing.sm,
  },
  flatPagerButton: {
    width: sizes.s28,
    height: sizes.s28,
    borderRadius: borderRadius.s14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  flatPagerText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  aboutText: {
    fontSize: 14.5,
    lineHeight: 20,
    color: colors.text,
  },
  detailCard: {
    backgroundColor: colors.glassSurface,
    borderRadius: semanticRadii.soft,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.s14,
    shadowOpacity: 0,
    elevation: 0,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailRowSpacing: {
    marginTop: spacing.md,
  },
  detailIcon: {
    width: sizes.s40,
    height: sizes.s40,
    borderRadius: semanticRadii.soft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.s12,
  },
  detailIconBlue: {
    backgroundColor: colors.infoLight,
  },
  detailIconGreen: {
    backgroundColor: colors.successSoft,
  },
  detailText: {
    flex: 1,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    letterSpacing: 0.6,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  mutedText: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  flatList: {
    gap: spacing.md,
  },
  flatCard: {
    borderRadius: semanticRadii.sheet,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    paddingHorizontal: spacing.s18,
    paddingVertical: spacing.md,
    backgroundColor: colors.glassSurface,
    paddingBottom: spacing.lg,
    overflow: 'hidden',
  },
  flatTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  flatMeta: {
    marginTop: spacing.s6,
    fontSize: 12,
    color: colors.text,
  },
  locationRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  locationChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s6,
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.chip,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primarySoft,
  },
  locationChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textStrong,
  },
  flatSection: {
    marginTop: spacing.md,
  },
  flatInfoBlock: {
    marginTop: spacing.s14,
    paddingVertical: spacing.sm,
    backgroundColor: 'transparent',
  },
  flatSubSection: {
    marginTop: spacing.s14,
  },
  flatSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textStrong,
    marginBottom: spacing.s10,
  },
  flatSubTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textStrong,
    marginBottom: spacing.sm,
  },
  listContainer: {
    gap: spacing.sm,
  },
  rulesToggle: {
    marginTop: spacing.s10,
    alignSelf: 'flex-start',
  },
  rulesToggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
    textDecorationLine: 'underline',
    textDecorationColor: colors.primaryMuted,
  },
  listItem: {
    fontSize: 12,
    lineHeight: 18,
    color: colors.text,
  },
  listBullet: {
    color: colors.textTertiary,
  },
  roomList: {
    gap: spacing.s10,
  },
  roomCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s12,
    padding: spacing.s12,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  roomPhoto: {
    width: semanticSizes.avatarMd,
    height: semanticSizes.avatarMd,
    borderRadius: borderRadius.s18,
    backgroundColor: colors.surfaceLight,
  },
  roomPhotoPlaceholder: {
    width: semanticSizes.avatarMd,
    height: semanticSizes.avatarMd,
    borderRadius: borderRadius.s18,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  roomInfo: {
    flex: 1,
  },
  roomHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  roomTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textStrong,
  },
  roomPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textStrong,
  },
  roomMeta: {
    marginTop: spacing.xs,
    fontSize: 12,
    color: colors.text,
  },
  roomFooter: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  statusBadge: {
    height: sizes.s24,
    paddingHorizontal: spacing.s12,
    borderRadius: semanticRadii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusAvailable: {
    backgroundColor: colors.successSoft,
  },
  statusOccupied: {
    backgroundColor: colors.errorSoft,
  },
  statusNeutral: {
    backgroundColor: colors.glassSurface,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  statusAvailableText: {
    color: colors.successDark,
  },
  statusOccupiedText: {
    color: colors.errorDark,
  },
  statusNeutralText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.text,
  },
  roomCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginLeft: 'auto',
  },
  roomCtaText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textStrong,
  },
  manageCard: {
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: spacing.md,
  },
  manageInfo: {
    marginBottom: spacing.s12,
  },
  manageTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
  },
  manageSubtitle: {
    marginTop: spacing.s6,
    fontSize: 13,
    color: colors.textSecondary,
  },
  manageButton: {
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.primary,
  },
  manageButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.background,
  },
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  outlineChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.s18,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  outlineChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.primary,
  },
  compactChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.s10,
  },
  compactChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.s14,
    paddingVertical: spacing.sm,
    borderRadius: semanticRadii.chip,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassUltraLightAlt,
  },
  compactChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  chipIcon: {
    marginRight: spacing.s6,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.s10,
    paddingVertical: spacing.s14,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.dangerStrong,
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  ctaButton: {
    marginBottom: spacing.xl,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.s18,
    paddingVertical: spacing.s14,
    alignItems: 'center',
  },
  ctaText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.background,
  },
  bottomActions: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    paddingHorizontal: spacing.s18,
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
  },
  bottomButton: {
    width: sizes.s58,
    height: sizes.s58,
    borderRadius: borderRadius.s29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  lightboxOverlay: {
    flex: 1,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightboxBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  lightboxContent: {
    width: '90%',
    height: '70%',
    borderRadius: semanticRadii.sheet,
    backgroundColor: colors.glassUltraLightAlt,
    borderWidth: 1,
    borderColor: colors.lavenderBorder,
    paddingHorizontal: spacing.s18,
    paddingVertical: spacing.s18,
    overflow: 'hidden',
  },
  lightboxTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s10,
  },
  lightboxTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  lightboxDivider: {
    height: 1,
    backgroundColor: colors.glassBorderSoft,
    marginBottom: spacing.s12,
  },
  lightboxClose: {
    paddingHorizontal: spacing.s10,
    height: sizes.s30,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxImageFrame: {
    flex: 1,
    borderRadius: semanticRadii.sheet,
    overflow: 'hidden',
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  lightboxImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  lightboxSlide: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.s12,
  },
  lightboxNavButton: {
    paddingHorizontal: spacing.s12,
    height: sizes.s36,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxCounterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  lightboxCounter: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textStrong,
  },
});
