import { StyleSheet } from 'react-native';
import {
  borderRadius,
  colors,
  semanticRadii,
  semanticSizes,
  sizes,
  spacing,
} from '../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surfaceMutedAlt,
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.glassBorderSoft,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  headerFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  headerSpacer: {
    width: sizes.s22,
  },
  pressed: {
    opacity: 0.75,
  },
  headerBackButton: {
    width: semanticSizes.control,
    height: semanticSizes.control,
    borderRadius: borderRadius.s18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  headerAction: {
    width: sizes.s32,
    height: sizes.s32,
    borderRadius: borderRadius.s16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.s20,
    paddingTop: spacing.s20,
  },
  carouselContainer: {
    marginBottom: spacing.lg,
  },
  carouselImage: {
    width: '100%',
    height: sizes.s320,
    borderRadius: semanticRadii.card,
    backgroundColor: colors.surfaceLight,
  },
  carouselDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: spacing.s10,
    gap: spacing.s6,
  },
  carouselDot: {
    width: spacing.s6,
    height: spacing.s6,
    borderRadius: borderRadius.xs,
    backgroundColor: colors.disabled,
  },
  carouselDotActive: {
    backgroundColor: colors.primary,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: spacing.s10,
  },
  detailCard: {
    backgroundColor: colors.glassSurface,
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    padding: spacing.md,
    gap: spacing.s12,
    shadowOpacity: 0,
    elevation: 0,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.s12,
  },
  detailLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s6,
    flexShrink: 1,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  detailValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'right',
    flexShrink: 1,
  },
  pricePill: {
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.indigoLight,
  },
  pricePillText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.indigoDark,
  },
  statusPill: {
    paddingHorizontal: spacing.s10,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
  },
  statusPillAvailable: {
    backgroundColor: colors.successSurface,
  },
  statusPillOccupied: {
    backgroundColor: colors.errorSoft,
  },
  statusPillText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  detailNote: {
    padding: spacing.s12,
    borderRadius: semanticRadii.soft,
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  detailNoteText: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
  },
  inviteRow: {
    marginTop: spacing.s12,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.s10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  inviteCopy: {
    flex: 1,
  },
  inviteTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text,
  },
  inviteSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  inviteHint: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: spacing.xs,
  },
  inviteOverlay: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  inviteCard: {
    borderRadius: semanticRadii.card,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    padding: spacing.lg,
    backgroundColor: colors.glassUltraLightAlt,
    overflow: 'hidden',
  },
  inviteCardFill: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.glassUltraLightAlt,
  },
  inviteHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
    marginBottom: spacing.s12,
  },
  inviteTitleText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  inviteCodeLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: spacing.xs,
  },
  inviteCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s10,
    justifyContent: 'space-between',
  },
  inviteCodeValue: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 1.2,
    flex: 1,
  },
  inviteCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.primaryMuted,
    backgroundColor: colors.primaryTint,
  },
  inviteCopyText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.primary,
  },
  inviteExpiresText: {
    marginTop: spacing.s10,
    fontSize: 12,
    color: colors.textSecondary,
  },
  inviteCloseButton: {
    marginTop: spacing.md,
    alignSelf: 'flex-end',
    paddingHorizontal: spacing.s16,
    paddingVertical: spacing.s8,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.surfaceLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  inviteCloseText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  lightboxOverlay: {
    flex: 1,
    backgroundColor: colors.overlayDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightboxBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  lightboxContent: {
    width: '90%',
    height: '70%',
    borderRadius: semanticRadii.sheet,
    backgroundColor: colors.glassUltraLightAlt,
    borderWidth: 1,
    borderColor: colors.lavenderBorder,
    paddingHorizontal: spacing.s18,
    paddingVertical: spacing.s18,
    overflow: 'hidden',
  },
  lightboxTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.s10,
  },
  lightboxTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  lightboxDivider: {
    height: 1,
    backgroundColor: colors.glassBorderSoft,
    marginBottom: spacing.s12,
  },
  lightboxClose: {
    paddingHorizontal: spacing.s10,
    height: sizes.s30,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxImageFrame: {
    flex: 1,
    borderRadius: semanticRadii.sheet,
    overflow: 'hidden',
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
  },
  lightboxImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  lightboxSlide: {
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing.s12,
  },
  lightboxNavButton: {
    paddingHorizontal: spacing.s12,
    height: sizes.s36,
    borderRadius: semanticRadii.pill,
    backgroundColor: colors.glassSurface,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lightboxCounterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.s12,
    paddingVertical: spacing.xs,
    borderRadius: semanticRadii.pill,
    borderWidth: 1,
    borderColor: colors.glassBorderSoft,
    backgroundColor: colors.glassSurface,
  },
  lightboxCounter: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textStrong,
  },
});
